# Copyright 2022 Criticality Score Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

algorithm: weighted_arithmetic_mean

inputs:
  - field: legacy.created_since
    weight: 1
    bounds:
      upper: 120
    distribution: zipfian

  - field: legacy.updated_since
    weight: 1
    bounds:
      upper: 120
      smaller_is_better: yes
    distribution: zipfian

  - field: legacy.contributor_count
    weight: 2
    bounds:
      upper: 5000
    distribution: zipfian

  - field: legacy.org_count
    weight: 1
    bounds:
      upper: 10
    distribution: zipfian

  - field: legacy.commit_frequency
    weight: 1
    bounds:
      upper: 1000
    distribution: zipfian

  - field: legacy.recent_release_count
    weight: 0.5
    bounds:
      upper: 26
    distribution: zipfian

  - field: legacy.updated_issues_count
    weight: 0.5
    bounds:
      upper: 5000
    distribution: zipfian

  - field: legacy.closed_issues_count
    weight: 0.5
    bounds:
      upper: 5000
    distribution: zipfian

  - field: legacy.issue_comment_frequency
    weight: 1
    bounds:
      upper: 15
    distribution: zipfian

  # If deps.dev dependenct count doesn't exist we use this configuration
  # for the GitHub search mention count.
  - field: legacy.github_mention_count
    weight: 2
    bounds:
      upper: 500000
    condition:
      not:
        field_exists: "depsdev.dependent_count"
    distribution: zipfian

  # If deps.dev dependent count *does* exist we lower the importance of
  # the GitHub search mention count.
  - field: legacy.github_mention_count
    weight: 1
    bounds:
      upper: 500000
    condition:
      field_exists: "depsdev.dependent_count"
    distribution: zipfian

  - field: depsdev.dependent_count
    weight: 4
    bounds:
      upper: 200000
    distribution: zipfian
